//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusGuiding.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DriverTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusGuiding.Resources.DriverTexts", typeof(DriverTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error locating the route.
        /// </summary>
        internal static string ErrorLocatingRoute {
            get {
                return ResourceManager.GetString("ErrorLocatingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehicle id field cannot be empty.
        /// </summary>
        internal static string ErrorVehicleIdEmpty {
            get {
                return ResourceManager.GetString("ErrorVehicleIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a for stop id:.
        /// </summary>
        internal static string ForStopIdLabel {
            get {
                return ResourceManager.GetString("ForStopIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enter your Vehicle ID and choose the route you will be working on..
        /// </summary>
        internal static string PleaseSelectRoute {
            get {
                return ResourceManager.GetString("PleaseSelectRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This message will be closed automatically..
        /// </summary>
        internal static string PopUpAutomaticallyClose {
            get {
                return ResourceManager.GetString("PopUpAutomaticallyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send GPS data.
        /// </summary>
        internal static string SendGPSOption {
            get {
                return ResourceManager.GetString("SendGPSOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a STOP REQUESTED.
        /// </summary>
        internal static string StopRequestedLabel {
            get {
                return ResourceManager.GetString("StopRequestedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System is now running. You can turn off this device screen, the application will turn it on..
        /// </summary>
        internal static string SystemRunningAdvice {
            get {
                return ResourceManager.GetString("SystemRunningAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route and Vehicle ID selection.
        /// </summary>
        internal static string TitleChoosingView {
            get {
                return ResourceManager.GetString("TitleChoosingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System running.
        /// </summary>
        internal static string TitleRunningView {
            get {
                return ResourceManager.GetString("TitleRunningView", resourceCulture);
            }
        }
    }
}
