//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusGuiding.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RiderTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RiderTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusGuiding.Resources.RiderTexts", typeof(RiderTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You arrived at destination! Thanks for using BusGuiding App..
        /// </summary>
        internal static string ArrivedAtDestinationAlert {
            get {
                return ResourceManager.GetString("ArrivedAtDestinationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to cancel this route?.
        /// </summary>
        internal static string CancelGuidingConfirmation {
            get {
                return ResourceManager.GetString("CancelGuidingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, a technical error happend during phase {0}.
        /// </summary>
        internal static string ErrorMessagePhase {
            get {
                return ResourceManager.GetString("ErrorMessagePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tab to find your nearest bus stop using your device GPD data..
        /// </summary>
        internal static string GeocaliseButtonHelpText {
            get {
                return ResourceManager.GetString("GeocaliseButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geolocation data cannot be got. Please try again..
        /// </summary>
        internal static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your bus is incoming at the origin stop, be prepared to get on..
        /// </summary>
        internal static string NotificationPh1Incoming {
            get {
                return ResourceManager.GetString("NotificationPh1Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A bus for you has been located, it is now in transit to the origin stop..
        /// </summary>
        internal static string NotificationPh1InTransit {
            get {
                return ResourceManager.GetString("NotificationPh1InTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your bus is about to arrive at destination, be prepared to get off..
        /// </summary>
        internal static string NotificationPh2IncomingDestination {
            get {
                return ResourceManager.GetString("NotificationPh2IncomingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your bus is now in transit to destination, be prepared to get off..
        /// </summary>
        internal static string NotificationPh2IntransitDestination {
            get {
                return ResourceManager.GetString("NotificationPh2IntransitDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route update.
        /// </summary>
        internal static string NotificationTitleRouteUpdate {
            get {
                return ResourceManager.GetString("NotificationTitleRouteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enter the origin stop code or tap the &apos;Geolocalise&apos; button..
        /// </summary>
        internal static string P2_EnterOriginStopLabel {
            get {
                return ResourceManager.GetString("P2-EnterOriginStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin stop selection.
        /// </summary>
        internal static string P2_Title {
            get {
                return ResourceManager.GetString("P2-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select the line you want to get on..
        /// </summary>
        internal static string P3_SelectRoute {
            get {
                return ResourceManager.GetString("P3-SelectRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line selection.
        /// </summary>
        internal static string P3_Title {
            get {
                return ResourceManager.GetString("P3-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select the destination stop where you want to get off..
        /// </summary>
        internal static string P4_SelectDestinationStop {
            get {
                return ResourceManager.GetString("P4-SelectDestinationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination stop selection.
        /// </summary>
        internal static string P4_Title {
            get {
                return ResourceManager.GetString("P4-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to travel from {0} to {1} by using the line {2}?.
        /// </summary>
        internal static string P4_TravelConfirmPrompt {
            get {
                return ResourceManager.GetString("P4-TravelConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By line:.
        /// </summary>
        internal static string P5_ByLineLabel {
            get {
                return ResourceManager.GetString("P5-ByLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route status.
        /// </summary>
        internal static string P5_RouteStatusLabel {
            get {
                return ResourceManager.GetString("P5-RouteStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route summary.
        /// </summary>
        internal static string P5_RouteSummaryLabel {
            get {
                return ResourceManager.GetString("P5-RouteSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In route.
        /// </summary>
        internal static string P5_Title {
            get {
                return ResourceManager.GetString("P5-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string P5_ToLabel {
            get {
                return ResourceManager.GetString("P5-ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Travelling from:.
        /// </summary>
        internal static string P5_TravellingFromLabel {
            get {
                return ResourceManager.GetString("P5-TravellingFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Routes cannot be got, please, check your internet connection.
        /// </summary>
        internal static string RoutesGettingError {
            get {
                return ResourceManager.GetString("RoutesGettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bus is about to arrive at the origin stop..
        /// </summary>
        internal static string StatusPh1Incoming {
            get {
                return ResourceManager.GetString("StatusPh1Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bus in transit to the origin stop..
        /// </summary>
        internal static string StatusPh1InTransit {
            get {
                return ResourceManager.GetString("StatusPh1InTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arriving at destination stop.
        /// </summary>
        internal static string StatusPh2IncomingDestination {
            get {
                return ResourceManager.GetString("StatusPh2IncomingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In transit to destination stop..
        /// </summary>
        internal static string StatusPh2IntransitDestination {
            get {
                return ResourceManager.GetString("StatusPh2IntransitDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In route. {0} stops remaining. Next stop is {1}.
        /// </summary>
        internal static string StatusPh2RemainingStops {
            get {
                return ResourceManager.GetString("StatusPh2RemainingStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for an incoming bus.
        /// </summary>
        internal static string StatusWaitingIncomingBus {
            get {
                return ResourceManager.GetString("StatusWaitingIncomingBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop code..
        /// </summary>
        internal static string StopCode {
            get {
                return ResourceManager.GetString("StopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter here the origin stop&apos;s code and tab the &quot;OK&quot; button..
        /// </summary>
        internal static string StopCodeHelpText {
            get {
                return ResourceManager.GetString("StopCodeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop not found.
        /// </summary>
        internal static string StopNotFoundError {
            get {
                return ResourceManager.GetString("StopNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line:.
        /// </summary>
        internal static string SummaryLine {
            get {
                return ResourceManager.GetString("SummaryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin stop:.
        /// </summary>
        internal static string SummaryOriginStop {
            get {
                return ResourceManager.GetString("SummaryOriginStop", resourceCulture);
            }
        }
    }
}
