//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusGuiding.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RiderTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RiderTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusGuiding.Resources.RiderTexts", typeof(RiderTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Geolocation data cannot be got. Please try again..
        /// </summary>
        internal static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enter the origin stop code or tap the &apos;Geolocalise&apos; button..
        /// </summary>
        internal static string P2_EnterOriginStopLabel {
            get {
                return ResourceManager.GetString("P2-EnterOriginStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin stop.
        /// </summary>
        internal static string P2_Title {
            get {
                return ResourceManager.GetString("P2-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select the line you want to get on..
        /// </summary>
        internal static string P3_SelectRoute {
            get {
                return ResourceManager.GetString("P3-SelectRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line selection.
        /// </summary>
        internal static string P3_Title {
            get {
                return ResourceManager.GetString("P3-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select the destination stop where you want to get off..
        /// </summary>
        internal static string P4_SelectDestinationStop {
            get {
                return ResourceManager.GetString("P4-SelectDestinationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destination stop.
        /// </summary>
        internal static string P4_Title {
            get {
                return ResourceManager.GetString("P4-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to travel from {0} to {1} by using the line {2}?.
        /// </summary>
        internal static string P4_TravelConfirmPrompt {
            get {
                return ResourceManager.GetString("P4-TravelConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By line:.
        /// </summary>
        internal static string P5_ByLineLabel {
            get {
                return ResourceManager.GetString("P5-ByLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route status.
        /// </summary>
        internal static string P5_RouteStatusLabel {
            get {
                return ResourceManager.GetString("P5-RouteStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Route summary.
        /// </summary>
        internal static string P5_RouteSummaryLabel {
            get {
                return ResourceManager.GetString("P5-RouteSummaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string P5_ToLabel {
            get {
                return ResourceManager.GetString("P5-ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Travelling from.
        /// </summary>
        internal static string P5_TravellingFromLabel {
            get {
                return ResourceManager.GetString("P5-TravellingFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Routes cannot be got, please, check your internet connection.
        /// </summary>
        internal static string RoutesGettingError {
            get {
                return ResourceManager.GetString("RoutesGettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop not found.
        /// </summary>
        internal static string StopNotFoundError {
            get {
                return ResourceManager.GetString("StopNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line:.
        /// </summary>
        internal static string SummaryLine {
            get {
                return ResourceManager.GetString("SummaryLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origin stop:.
        /// </summary>
        internal static string SummaryOriginStop {
            get {
                return ResourceManager.GetString("SummaryOriginStop", resourceCulture);
            }
        }
    }
}
